### ISSUE TITLE
Question about loss

### ISSUE THREAD

**Issue by catalys1** [pclucas14/pytorch-glow#3]
You define the loss per image to be
```python
nll = (-objective) / float(np.log(2.) * np.prod(img.shape[1:]))
```
My question is where the `log(2)` factor comes from. I don't see it in equation 2 in the paper.

**Comment by pclucas14** [comment]
Hi Connor, 

Good question! I actually took this from the [official implementation](https://github.com/openai/glow/blob/master/model.py#L185). It seems that this is to account for the change of basis in the log (from e to 2) as discussed [here](https://www.reddit.com/r/MachineLearning/comments/56m5o2/discussion_calculation_of_bitsdims/)

Hope this helps!
Lucas
